name: edm_from_unet_adm

image_size: 64
num_channels: 128
num_res_blocks: 1
channel_mult: ""
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
resblock_updown: True
use_fp16: False
use_new_attention_order: False
model_path: path/to/blackhole.pt
grayscale: True

diffusion:
  img_resolution: 256
  img_channels: 1
  beta_min: 0.1
  beta_d: 19.9
  M: 1000