title: Awesome Computational Imaging
author: Xueqing Gao

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_image

html_theme: sphinx_book_theme
